### ISSUE TITLE
'terraform fmt' runs only for 'pull_request' event and does not show error logs during exit

### ISSUE THREAD

**Issue by Nimesha-Premaraja** [suzuki-shunsuke/github-action-format#582]
### Description:

During a workflow run [here](https://github.com/suzuki-shunsuke/github-action-format/blob/main/main.sh#L12) the `terraform format` command will get success only when **EVENT_NAME** is a `pull_request` event.

### Actual Behavior:

1. The `terraform format` runs only for `pull_request`. This may cause for credential theft from forked repositories.
2. Does not show valid error logs / information during workflow failures for terraform fmt. 

### Expected Behavior:

1. The `terraform format` should be run on both `pull_request` and `pull_request_target`.` This means the workflow is running from a trusted source and is given access to a read/write token as well as secrets enabling the maintainer to safely comment on or label a pull request.
```
# Check if EVENT_NAME is either pull_request or pull_request_target
if [ "$EVENT_NAME" != "pull_request" ] && [ "$EVENT_NAME" != "pull_request_target" ]; then
    { echo "Error: Invalid event name. Expected either 'pull_request' or 'pull_request_target'."; exit 1; }
fi
```

2. Exit messages must be added to the exit code in order to identity workflow failures and further debugging. 

Sample error logs
```
Run bash /home/runner/work/_actions/org_name/github-action-format/main/main.sh
…
INPUT_COMMIT_MESSAGE: style: terraform fmt -recursive
EVENT_NAME: pull_request_target
Error: Invalid event name. Expected either 'pull_request' or 'pull_request_target'.
Error: Process completed with exit code 1.
```

**Comment by Nimesha-Premaraja** [comment]
Pull Request: https://github.com/suzuki-shunsuke/github-action-format/pull/583 has been raised for this

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/github-action-format/pull/586
- https://github.com/suzuki-shunsuke/github-action-format/pull/590

**Comment by suzuki-shunsuke** [comment]
v0.2.0 is out 🎉
The issue has been solved.
https://github.com/suzuki-shunsuke/github-action-format/releases/tag/v0.2.0

**Comment by Nimesha-Premaraja** [comment]
Thank you @suzuki-shunsuke
